// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZAbANF7vRXu4XoNrrOOqILIC-IfAE7II',
    appId: '1:1095405167345:web:8d88fffa3e8f383628ff50',
    messagingSenderId: '1095405167345',
    projectId: 'test-e842d',
    authDomain: 'test-e842d.firebaseapp.com',
    storageBucket: 'test-e842d.firebasestorage.app',
    measurementId: 'G-3EZYEBXXZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsTaEH_gZE1MzUbVh6EUQmU26gGRhIuQ4',
    appId: '1:1095405167345:android:61b52a4da393b0bd28ff50',
    messagingSenderId: '1095405167345',
    projectId: 'test-e842d',
    storageBucket: 'test-e842d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxgh0zQIlBDIEe9e9BicF7YAQoRXNmFlQ',
    appId: '1:1095405167345:ios:f5fc6a6866534d2c28ff50',
    messagingSenderId: '1095405167345',
    projectId: 'test-e842d',
    storageBucket: 'test-e842d.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxgh0zQIlBDIEe9e9BicF7YAQoRXNmFlQ',
    appId: '1:1095405167345:ios:f5fc6a6866534d2c28ff50',
    messagingSenderId: '1095405167345',
    projectId: 'test-e842d',
    storageBucket: 'test-e842d.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZAbANF7vRXu4XoNrrOOqILIC-IfAE7II',
    appId: '1:1095405167345:web:1b39593876d1733a28ff50',
    messagingSenderId: '1095405167345',
    projectId: 'test-e842d',
    authDomain: 'test-e842d.firebaseapp.com',
    storageBucket: 'test-e842d.firebasestorage.app',
    measurementId: 'G-F9VB93DE5B',
  );
}
